# Generated by Django 5.0.2 on 2024-05-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='name',
            new_name='stock_number',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='desk_type',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='monitor',
        ),
        migrations.AddField(
            model_name='desk',
            name='monitor_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='desk',
            name='power_socket_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
