# Generated by Django 5.0.3 on 2024-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="desk",
            old_name="name",
            new_name="stock_number",
        ),
        migrations.RemoveField(
            model_name="desk",
            name="desk_type",
        ),
        migrations.RemoveField(
            model_name="desk",
            name="monitor",
        ),
        migrations.AddField(
            model_name="desk",
            name="monitor_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="desk",
            name="power_socket_count",
            field=models.IntegerField(default=1),
        ),
    ]
