# Generated by Django 5.0.2 on 2024-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description_1_subtitle', models.TextField(default='Insert your title for first paragraph...')),
                ('description_1', models.TextField(default="Insert your first paragraph's description...")),
                ('description_2_subtitle', models.TextField(blank=True, default='')),
                ('description_2', models.TextField(blank=True, default='')),
                ('description_3_subtitle', models.TextField(blank=True, default='')),
                ('description_3', models.TextField(blank=True, default='')),
                ('description_4_subtitle', models.TextField(blank=True, default='')),
                ('description_4', models.TextField(blank=True, default='')),
                ('description_5_subtitle', models.TextField(blank=True, default='')),
                ('description_5', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
