# Generated by Django 5.0.2 on 2024-05-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0002_rename_name_desk_stock_number_remove_desk_desk_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OurOffer',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coapp.singletonmodel')),
                ('title', models.CharField(max_length=50)),
                ('description_1_subtitle', models.TextField(default='Insert your title for first paragraph...')),
                ('description_1', models.TextField(default="Insert your first paragraph's description...")),
                ('description_2_subtitle', models.TextField(blank=True, default='')),
                ('description_2', models.TextField(blank=True, default='')),
            ],
            bases=('coapp.singletonmodel',),
        ),
    ]
