# Generated by Django 5.0.2 on 2024-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description_1_subtitle', models.TextField(default='Insert your title for first paragraph...')),
                ('description_1', models.TextField(default="Insert your first paragraph's description...")),
                ('description_2_subtitle', models.TextField(blank=True, default='')),
                ('description_2', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
