# Generated by Django 5.0.2 on 2024-05-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0003_singletonmodel_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
