# Generated by Django 5.0.2 on 2024-05-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0003_servicerules_delete_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRules',
            new_name='ServiceRule',
        ),
    ]
