# Generated by Django 5.0.3 on 2024-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coapp", "0003_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desk",
            name="monitor_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="desk",
            name="power_socket_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="desk",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
