# Generated by Django 5.0.2 on 2024-05-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0004_rename_servicerules_servicerule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceRule',
            new_name='ServiceTerm',
        ),
    ]
