# Generated by Django 5.0.2 on 2024-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0005_rename_servicerule_serviceterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceterm',
            name='description_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceterm',
            name='description_3_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceterm',
            name='description_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceterm',
            name='description_4_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceterm',
            name='description_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceterm',
            name='description_5_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
